# Generated by Django 2.2.4 on 2021-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.SmallIntegerField()),
                ('delivery', models.NullBooleanField()),
                ('resource', models.SmallIntegerField()),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
