# Generated by Django 2.2.4 on 2021-04-30 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_auto_20210430_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
