# Generated by Django 2.2.4 on 2021-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20210430_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
